/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentation;

import Domain.Client;
import Domain.DataBase;
import Logic.Binnacle;
import Logic.Transaction;
import java.io.IOException;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author afern
 */
public class JFInterface extends javax.swing.JFrame {

    /**
     * Creates new form JFInterface
     */
    
    private DataBase database;
    private Client selectedClient;
    private Binnacle binnacle;
    private int menu;
    
    
    public JFInterface() {
        
        this.setResizable(false);
        this.database = new DataBase();
        this.selectedClient = this.database.getClients().get(0);
        this.binnacle = new Binnacle();
        initComponents();
        this.jPanelClientInterface.removeAll();
        menu1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanelClientInterface = new javax.swing.JPanel();
        jLabelUserFace = new javax.swing.JLabel();
        jLabelClientName = new javax.swing.JLabel();
        jPanelClientAccount = new javax.swing.JPanel();
        jLabelBalance = new javax.swing.JLabel();
        jLabelAccountNumber = new javax.swing.JLabel();
        jLabelAccounts = new javax.swing.JLabel();
        jButtonSeeMyAccounts = new javax.swing.JButton();
        jButtonSinpeMovil = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jTextFieldSinpeMovilNumber = new javax.swing.JTextField();
        jTextFieldAmount = new javax.swing.JTextField();
        jComboBoxAccountSelection = new javax.swing.JComboBox<>();
        jTextFieldDetails = new javax.swing.JTextField();
        jLabelSinpeMovilTitle = new javax.swing.JLabel();
        jButtonValidate = new javax.swing.JButton();
        jLabelDebitTo = new javax.swing.JLabel();
        jButtonState = new javax.swing.JButton();
        jComboBoxUser = new javax.swing.JComboBox<>();
        jLabelTesterTools = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelClientInterface.setBackground(new java.awt.Color(255, 255, 255));

        jLabelUserFace.setBackground(new java.awt.Color(51, 51, 51));
        jLabelUserFace.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserFace.setText("  USER FACE");
        jLabelUserFace.setOpaque(true);

        jLabelClientName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelClientName.setForeground(new java.awt.Color(0, 0, 102));
        jLabelClientName.setText(this.selectedClient.getName().toUpperCase());

        jPanelClientAccount.setBackground(new java.awt.Color(255, 255, 255));
        jPanelClientAccount.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelBalance.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelBalance.setForeground(new java.awt.Color(0, 204, 204));
        jLabelBalance.setText("₡ "+this.selectedClient.getAccounts().get(0).getBalance());

        jLabelAccountNumber.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelAccountNumber.setForeground(new java.awt.Color(0, 0, 102));
        jLabelAccountNumber.setText(this.selectedClient.getAccounts().get(0).getAccountNumber());

        javax.swing.GroupLayout jPanelClientAccountLayout = new javax.swing.GroupLayout(jPanelClientAccount);
        jPanelClientAccount.setLayout(jPanelClientAccountLayout);
        jPanelClientAccountLayout.setHorizontalGroup(
            jPanelClientAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClientAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientAccountLayout.createSequentialGroup()
                        .addComponent(jLabelAccountNumber)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientAccountLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelBalance)))
                .addContainerGap())
        );
        jPanelClientAccountLayout.setVerticalGroup(
            jPanelClientAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAccountNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabelBalance))
        );

        jLabelAccounts.setForeground(new java.awt.Color(0, 0, 102));
        jLabelAccounts.setText("Accounts");

        jButtonSeeMyAccounts.setText("See my accounts >");
        jButtonSeeMyAccounts.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonSeeMyAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeMyAccountsActionPerformed(evt);
            }
        });

        jButtonSinpeMovil.setText("SINPE MOVIL");
        jButtonSinpeMovil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSinpeMovilMouseClicked(evt);
            }
        });
        jButtonSinpeMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinpeMovilActionPerformed(evt);
            }
        });

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jTextFieldSinpeMovilNumber.setForeground(new java.awt.Color(0, 0, 102));
        jTextFieldSinpeMovilNumber.setText("SINPE Movil phone number");
        jTextFieldSinpeMovilNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSinpeMovilNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSinpeMovilNumberFocusLost(evt);
            }
        });
        jTextFieldSinpeMovilNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSinpeMovilNumberActionPerformed(evt);
            }
        });
        jTextFieldSinpeMovilNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSinpeMovilNumberKeyTyped(evt);
            }
        });

        jTextFieldAmount.setForeground(new java.awt.Color(0, 0, 102));
        jTextFieldAmount.setText("Amount");
        jTextFieldAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAmountFocusLost(evt);
            }
        });
        jTextFieldAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAmountKeyTyped(evt);
            }
        });

        jComboBoxAccountSelection.setModel(new javax.swing.DefaultComboBoxModel<>(loadAccounts()));
        jComboBoxAccountSelection.setOpaque(true);

        jTextFieldDetails.setForeground(new java.awt.Color(0, 0, 102));
        jTextFieldDetails.setText("Details");
        jTextFieldDetails.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDetailsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDetailsFocusLost(evt);
            }
        });

        jLabelSinpeMovilTitle.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 24)); // NOI18N
        jLabelSinpeMovilTitle.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSinpeMovilTitle.setText("SINPE Movil");

        jButtonValidate.setText("Validate");
        jButtonValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidateActionPerformed(evt);
            }
        });

        jLabelDebitTo.setForeground(new java.awt.Color(0, 0, 102));
        jLabelDebitTo.setText("Debit to:");

        jButtonState.setText("STATE");
        jButtonState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStateActionPerformed(evt);
            }
        });

        jComboBoxUser.setModel(new javax.swing.DefaultComboBoxModel<>(loadUsers()));
        jComboBoxUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUserActionPerformed(evt);
            }
        });

        jLabelTesterTools.setText("Tester Tools");

        javax.swing.GroupLayout jPanelClientInterfaceLayout = new javax.swing.GroupLayout(jPanelClientInterface);
        jPanelClientInterface.setLayout(jPanelClientInterfaceLayout);
        jPanelClientInterfaceLayout.setHorizontalGroup(
            jPanelClientInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientInterfaceLayout.createSequentialGroup()
                .addGroup(jPanelClientInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClientInterfaceLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanelClientInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelClientInterfaceLayout.createSequentialGroup()
                                .addGroup(jPanelClientInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonState)
                                    .addComponent(jComboBoxUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTesterTools))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonBack))
                            .addComponent(jButtonSeeMyAccounts, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAccounts)
                            .addComponent(jPanelClientAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelClientInterfaceLayout.createSequentialGroup()
                                .addComponent(jLabelUserFace, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelClientInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelClientInterfaceLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelClientInterfaceLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabelSinpeMovilTitle))))
                            .addGroup(jPanelClientInterfaceLayout.createSequentialGroup()
                                .addComponent(jButtonSinpeMovil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelDebitTo))
                            .addComponent(jTextFieldSinpeMovilNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                            .addComponent(jTextFieldAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxAccountSelection, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDetails, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanelClientInterfaceLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButtonValidate)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelClientInterfaceLayout.setVerticalGroup(
            jPanelClientInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientInterfaceLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelClientInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClientInterfaceLayout.createSequentialGroup()
                        .addComponent(jLabelUserFace, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabelAccounts))
                    .addGroup(jPanelClientInterfaceLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelClientName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSinpeMovilTitle)))
                .addGap(11, 11, 11)
                .addComponent(jPanelClientAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSeeMyAccounts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClientInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSinpeMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDebitTo))
                .addGap(9, 9, 9)
                .addComponent(jComboBoxAccountSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTextFieldSinpeMovilNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonValidate)
                .addGap(66, 66, 66)
                .addComponent(jLabelTesterTools)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonState)
                .addGap(10, 10, 10)
                .addGroup(jPanelClientInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelClientInterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelClientInterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String[] loadAccounts(){
        ArrayList<String> accString = new ArrayList<String>();
        for (int i = 0; i < this.selectedClient.getAccounts().size(); i++) {
            accString.add(this.selectedClient.getAccounts().get(i).getAccountNumber());
        }
        return Arrays.copyOf(accString.toArray(), accString.toArray().length, String[].class);
    }
    
    private String[] loadUsers(){
        ArrayList<String> userString = new ArrayList<String>();
        for (int i = 0; i < this.database.getClients().size(); i++) {
            userString.add(this.database.getClients().get(i).getId() + " " + this.database.getClients().get(i).getName());
        }
        return Arrays.copyOf(userString.toArray(), userString.toArray().length, String[].class);
    }
    
    private void menu1(){
        this.menu = 1;
        this.jPanelClientInterface.removeAll();
        this.jPanelClientInterface.add(this.jButtonSinpeMovil);
        this.jPanelClientInterface.add(this.jButtonSeeMyAccounts);
        this.jPanelClientInterface.add(this.jLabelUserFace);
        this.jPanelClientInterface.add(this.jLabelClientName);
        this.jPanelClientInterface.add(this.jLabelAccounts);
        this.jPanelClientInterface.add(this.jPanelClientAccount);
        this.jPanelClientInterface.add(this.jButtonBack);
        
        this.jPanelClientInterface.add(this.jLabelTesterTools);
        this.jPanelClientInterface.add(this.jComboBoxUser);
        this.jPanelClientInterface.add(this.jButtonState);
        this.jPanelClientInterface.add(this.jButtonBack);
        repaint();
    }//menu1
    
    private void menu2(){
        this.menu = 2;
        this.jPanelClientInterface.removeAll();
        this.jPanelClientInterface.add(this.jComboBoxAccountSelection);
        this.jPanelClientInterface.add(this.jTextFieldSinpeMovilNumber);
        this.jPanelClientInterface.add(this.jTextFieldAmount);
        this.jPanelClientInterface.add(this.jTextFieldDetails);
        this.jPanelClientInterface.add(this.jButtonValidate);
        
        this.jPanelClientInterface.add(this.jLabelSinpeMovilTitle);
        this.jPanelClientInterface.add(this.jLabelDebitTo);
        
        this.jPanelClientInterface.add(this.jLabelTesterTools);
        this.jPanelClientInterface.add(this.jComboBoxUser);
        this.jPanelClientInterface.add(this.jButtonBack);
        this.jPanelClientInterface.add(this.jButtonState);
        repaint();
    }//menu2
    
    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        if (this.menu!= 1) {
            menu1();
        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonSeeMyAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeMyAccountsActionPerformed
        // TODO add your handling code here:
  
        
    }//GEN-LAST:event_jButtonSeeMyAccountsActionPerformed

    private void jButtonSinpeMovilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSinpeMovilMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonSinpeMovilMouseClicked

    private void jButtonSinpeMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinpeMovilActionPerformed
        // TODO add your handling code here:
        menu2();
        
    }//GEN-LAST:event_jButtonSinpeMovilActionPerformed

    private void jTextFieldSinpeMovilNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSinpeMovilNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSinpeMovilNumberActionPerformed

    private void jTextFieldSinpeMovilNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSinpeMovilNumberFocusGained
        // TODO add your handling code here:
        if (jTextFieldSinpeMovilNumber.getText().equals("SINPE Movil phone number")) {
            this.jTextFieldSinpeMovilNumber.setText(""); 
        }  
    }//GEN-LAST:event_jTextFieldSinpeMovilNumberFocusGained

    private void jTextFieldSinpeMovilNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSinpeMovilNumberFocusLost
        // TODO add your handling code here:
        if (jTextFieldSinpeMovilNumber.getText().equals("")) {
            this.jTextFieldSinpeMovilNumber.setText("SINPE Movil phone number");
        }//if
    }//GEN-LAST:event_jTextFieldSinpeMovilNumberFocusLost

    private void jTextFieldAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAmountFocusGained
        // TODO add your handling code here:
        if (jTextFieldAmount.getText().equals("Amount")) {
            this.jTextFieldAmount.setText(""); 
        }  
    }//GEN-LAST:event_jTextFieldAmountFocusGained

    private void jTextFieldAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAmountFocusLost
        // TODO add your handling code here:
        if (jTextFieldAmount.getText().equals("")) {
            this.jTextFieldAmount.setText("Amount");
        }//if
    }//GEN-LAST:event_jTextFieldAmountFocusLost

    private void jTextFieldDetailsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDetailsFocusGained
        // TODO add your handling code here:
        if (jTextFieldDetails.getText().equals("Details")) {
            this.jTextFieldDetails.setText(""); 
        }  
 
    }//GEN-LAST:event_jTextFieldDetailsFocusGained

    private void jTextFieldDetailsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDetailsFocusLost
        // TODO add your handling code here:
        if (jTextFieldDetails.getText().equals("")) {
            this.jTextFieldDetails.setText("Details");
        }//if 
    }//GEN-LAST:event_jTextFieldDetailsFocusLost

    private void jButtonValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidateActionPerformed
        // TODO add your handling code here:
        
        if (validateInputs()) {
            Client targetClient = this.database.searchClientByPhone(this.jTextFieldSinpeMovilNumber.getText());
            Transaction transaction = new Transaction(selectedClient,
                    targetClient,
                    Double.parseDouble(this.jTextFieldAmount.getText()),
                    this.jTextFieldDetails.getText(),
                    this.jComboBoxAccountSelection.getSelectedIndex());
            try {
                if (targetClient != null) {
                    if (this.binnacle.binnacleWriter(transaction.getVoucher())) {
                    transaction.getVoucher().printVoucher();
                    this.jLabelAccountNumber.setText(this.selectedClient.getAccounts().get(0).getAccountNumber());
                    this.jLabelBalance.setText("₡ "+this.selectedClient.getAccounts().get(0).getBalance());
                    }else JOptionPane.showMessageDialog(null, "ERROR WHILE CREATING THE VOUCHER", "ERROR", JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "CLIENT NOT FOUND", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(JFInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
   
        }else{
            JOptionPane.showMessageDialog(null, "EMPTY FIELDS", "WARNING", JOptionPane.INFORMATION_MESSAGE);
           
        }  
    }//GEN-LAST:event_jButtonValidateActionPerformed

    private void jTextFieldSinpeMovilNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSinpeMovilNumberKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) evt.consume();
    }//GEN-LAST:event_jTextFieldSinpeMovilNumberKeyTyped

    private void jTextFieldAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAmountKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) evt.consume();
    }//GEN-LAST:event_jTextFieldAmountKeyTyped

    private void jButtonStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStateActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, this.database.toString(), "Current state", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButtonStateActionPerformed

    private void jComboBoxUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUserActionPerformed
        // TODO add your handling code here:
        
        this.selectedClient = this.database.getClients().get(this.jComboBoxUser.getSelectedIndex());
        this.jLabelClientName.setText(this.selectedClient.getName().toUpperCase());
        this.jComboBoxAccountSelection.setModel(new javax.swing.DefaultComboBoxModel<>(this.loadAccounts()));
        this.jLabelAccountNumber.setText(this.selectedClient.getAccounts().get(0).getAccountNumber());
        this.jLabelBalance.setText("₡ "+this.selectedClient.getAccounts().get(0).getBalance());
        
    }//GEN-LAST:event_jComboBoxUserActionPerformed

    public boolean validateInputs(){
        
        if (this.jTextFieldSinpeMovilNumber.getText().equals("SINPE Movil number")) {
            return false;
        }//if
       
        if (this.jTextFieldAmount.getText().equals("Amount")) {
            return false;
        }//if
        
        if (this.jTextFieldDetails.getText().equals("Details")) {
            return false;
        }//if
        
        for (int i = 0; i < this.jTextFieldAmount.getText().length(); i++){
            char c = this.jTextFieldAmount.getText().charAt(i);
            if (c < '0' || c > '9') {
                return false;
            }//if
        }//for
        return true;
    }
    
    public DataBase getDatabase() {
        return database;
    }

    public void setDatabase(DataBase database) {
        this.database = database;
    }
    
    public int getMenu() {
        return menu;
    }

    public void setMenu(int menu) {
        this.menu = menu;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSeeMyAccounts;
    private javax.swing.JButton jButtonSinpeMovil;
    private javax.swing.JButton jButtonState;
    private javax.swing.JButton jButtonValidate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxAccountSelection;
    private javax.swing.JComboBox<String> jComboBoxUser;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAccountNumber;
    private javax.swing.JLabel jLabelAccounts;
    private javax.swing.JLabel jLabelBalance;
    private javax.swing.JLabel jLabelClientName;
    private javax.swing.JLabel jLabelDebitTo;
    private javax.swing.JLabel jLabelSinpeMovilTitle;
    private javax.swing.JLabel jLabelTesterTools;
    private javax.swing.JLabel jLabelUserFace;
    private javax.swing.JPanel jPanelClientAccount;
    private javax.swing.JPanel jPanelClientInterface;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldDetails;
    private javax.swing.JTextField jTextFieldSinpeMovilNumber;
    // End of variables declaration//GEN-END:variables
}
